package com.doganmehmet.app.enums;

public enum LogType {
    REGISTER ,LOGIN, LOGOUT, INCORRECT_PASSWORD,
    ALREADY_EXISTS_EXCEPTION, NOT_FOUND_EXCEPTION,
    SUCCESSFUL,
    SALARY_UPDATE, LEAVE_REQUEST, ACCOUNT_LOCKED,
    CREATE_TOKENS, TOKEN_EXPIRED, TOKEN_REFRESH
}
